---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:16.14.2
  commands:
  - npm ci


- name: test
  image: node:16.14.2
  commands:
  - npm run test